const cookies = [
  {
    name: 'fr',
    value:
      '0g5CqLPKlzPiPDCUx.AWXlM9Obg0LwEPTQCoIb2cOXpsI.BlSu-7.iz.AAA.0.0.BlSu-9.AWWtyRmmjjg',
    domain: '.facebook.com',
    path: '/',
    expires: 1707185854.982983,
    size: 84,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'xs',
    value: '27%3ARKbsogy3CeH4yQ%3A2%3A1699409853%3A-1%3A-1',
    domain: '.facebook.com',
    path: '/',
    expires: 1730945854.98294,
    size: 48,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'datr',
    value: 'u-9KZUt4Xsn1b8ivMOo1y3xG',
    domain: '.facebook.com',
    path: '/',
    expires: 1733969851.878351,
    size: 28,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'c_user',
    value: '61553415145673',
    domain: '.facebook.com',
    path: '/',
    expires: 1730945854.982895,
    size: 20,
    httpOnly: false,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'wd',
    value: '800x600',
    domain: '.facebook.com',
    path: '/',
    expires: 1700014656,
    size: 9,
    httpOnly: false,
    secure: true,
    session: false,
    sameSite: 'Lax',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'sb',
    value: 'u-9KZc9lDEJuoO2YKV9RdSgU',
    domain: '.facebook.com',
    path: '/',
    expires: 1733969854.982779,
    size: 26,
    httpOnly: true,
    secure: true,
    session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
];

export { cookies };
