export enum MediaFileStatus {
  UPLOADING = 'UPLOADING',
  UPLOADED = 'UPLOADED',
  TRANSCODING = 'TRANSCODING',
  DONE = 'DONE',
  ERROR = 'ERROR',
}

export enum MediaStatus {
  UPLOADING = 'UPLOADING',
  UPLOADED = 'UPLOADED',
  TRANSCODING = 'TRANSCODING',
  DONE = 'DONE',
  ERROR = 'ERROR',
}
